### ISSUE TITLE
Copy Share Link Not Working

### ISSUE THREAD

**Issue by dnburgess** [ybizeul/hupload#14]
I've tried in multiple browser and multiple systems and the copy share URL button isn't working for me.

Made a quick video about it here:

https://youtu.be/GuiCqxjFsm4

**Comment by ybizeul** [comment]
I was able to confirm. I'll made feedback more clear to the user, or remove the copy link options if on http

**Comment by dnburgess** [comment]
Glad you were able to confirm. Feel free to mark as closed if you want. Just wanted to call attention to this.
