### ISSUE TITLE
Able to Upload to Share Without Being Logged In

### ISSUE THREAD

**Issue by dnburgess** [ybizeul/hupload#15]
I've tried in multiple browser and multiple systems and am able to upload to existing shares without being logged in

Made a quick video about it here:

https://youtu.be/XdsSZ62tfRg

**Comment by ybizeul** [comment]
Yes, that's actually the point of hupload :-)

The link for a share is kind of private and randomly generated, that's your security, that way, you don't have to ask users to create an account to be able to upload.

**Comment by dnburgess** [comment]
Fair enough. Looking forward to updates :)
